"""empty message

Revision ID: b3ba90a2a952
Revises: bd9d168c80a7
Create Date: 2020-10-07 07:47:03.060399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ba90a2a952'
down_revision = 'bd9d168c80a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('title', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'title')
    # ### end Alembic commands ###
