"""empty message

Revision ID: c037256e84bc
Revises: 0079f692427e
Create Date: 2020-10-10 11:12:15.781463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c037256e84bc'
down_revision = '0079f692427e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Test_score', sa.INTEGER(), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=False),
    sa.Column('date_certif', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('Certif_ref', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
